<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 0" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="E:\git\python-ote\workspace\pythonfirst\BeautifulSoup&amp;#33539;&amp;#20363;\BeautifulSoup&amp;#65288;&amp;#65289;.py" status="error" test="BeautifulSoup&amp;#65288;&amp;#65289;" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "D:\gongzuo\eclipse2\eclipse\plugins\org.python.pydev_5.0.0.201605051159\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "E:/git/python-ote/workspace/pythonfirst/BeautifulSoup&#33539;&#20363;\BeautifulSoup&#65288;&#65289;.py", line 13, in <module>
    print(html)
UnicodeEncodeError: 'gbk' codec can't encode character '\u02c8' in position 161: illegal multibyte sequence
ERROR: Module: BeautifulSoup&#65288;&#65289; could not be imported (file: E:\git\python-ote\workspace\pythonfirst\BeautifulSoup&#33539;&#20363;\BeautifulSoup&#65288;&#65289;.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="pythonfirst BeautifulSoup（）.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
